title: Julio Sebastián De La Trinidad Rendón
email: your.email@example.com
description: >-
  Mechatronics Engineer | PhD Student in Engineering Sciences | Researcher in Autonomous Mobile Robots
baseurl: ""
url: "https://JulesDeLaT-ITESM.github.io"
twitter_username: yourtwitter
github_username: JulesDeLaT-ITESM
linkedin_username: yourlinkedin

# Build settings
remote_theme: mmacneil/devfolio
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  
header_pages:
  - index.md
  - research.md
  - publications.md

# Site settings
accent_color: '#4C60E6'
accent_image: /assets/img/sidebar-bg.jpg
