title: Julio Sebastián De La Trinidad Rendón
description: >- # this means to ignore newlines until "baseurl:"
  Mechatronics Engineer | PhD Student in Engineering Sciences | Researcher in Autonomous Mobile Robots
theme: jekyll-theme-cayman
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://JulesDeLaT-ITESM.github.io" # the base hostname & protocol for your site
github_username: JulesDeLaT-ITESM
linkedin_username: julio-sebastian-de-la-trinidad
scholar_id: YOUR_GOOGLE_SCHOLAR_ID

# Build settings
markdown: kramdown
include:
  - _includes
